version: '2'
services:
  proyecto_monitoreo-mongodb:
    image: mongo:4.2.3
    ports:
      - '27017:27017'
    command: mongos --configdb proyecto_monitoreo-mongodb-config
  proyecto_monitoreo-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  proyecto_monitoreo-mongodb-config:
    image: mongo:4.2.3
    container_name: proyecto_monitoreo-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
